### ISSUE TITLE
Seems no update

### ISSUE THREAD

**Issue by niamulrox** [django-erp/django-erp#27]
Its totally old now , No new update , Is there anyone working on it ? I had installed and there comments , markup and formtools already depricated but I tried to install as external but fail then commented that dependency and installed ok but I did not able to see anything or unable to login ... Its only saying 

#A server error occurred.  Please contact the administrator.

**Comment by zuck** [comment]
Hi @niamulrox,

the answer is **no**: there is nobody working on this project at the moment. I'm sorry for that.

By the way, as an open-source project, I'm open to every kind of suggestion/discussion/PR.

Feel free to contribute if you'd like!

I close this issue in favor of #28, please if you want to contribute to the project, put a comment there.

Thank you for your feedback!
