### ISSUE TITLE
Migration cannot be done 

### ISSUE THREAD

**Issue by vsakunni** [django-erp/django-erp#35]
While migrating it displays 'Apps arent loaded yet'
![issue](https://user-images.githubusercontent.com/29794745/59771820-2d249f00-92c8-11e9-8f61-92125e331cfa.PNG)

**Comment by rashedomar** [comment]
same issue

**Comment by ahmedelhawary** [comment]
Try to add this lines to the top of your settings file:

import django
django.setup()
And if this will not help you try to remove third-party applications from your installed apps list one-by-one.

**Comment by santoshmswami** [comment]
D:\django-erp>dir
 Volume in drive D is Lenovo_Recovery
 Volume Serial Number is E8ED-E894

 Directory of D:\django-erp

06/06/2020  08:08PM    <DIR>          .
06/06/2020  08:08PM    <DIR>          ..
06/06/2020  08:08PM               557 .gitignore
06/06/2020  08:08PM               451 .travis.yml
06/06/2020  08:08PM    <DIR>          djangoerp
06/06/2020  08:08PM    <DIR>          docs
06/06/2020  08:08PM             1,100 LICENSE
06/06/2020  08:33PM               291 manage.py
06/06/2020  08:08PM             2,164 README.md
06/06/2020  08:08PM                52 requirements.txt
06/06/2020  08:08PM             1,640 update_version.py
               

D:\django-erp>python manage migrate
python: can't open file 'manage': [Errno 2] No such file or directory

**Comment by santoshmswami** [comment]
D:\django-erp>dir
 Volume in drive D is Lenovo_Recovery
 Volume Serial Number is E8ED-E894

 Directory of D:\django-erp

06/06/2020  08:08PM    <DIR>          .
06/06/2020  08:08PM    <DIR>          ..
06/06/2020  08:08PM               557 .gitignore
06/06/2020  08:08PM               451 .travis.yml
06/06/2020  08:08PM    <DIR>          djangoerp
06/06/2020  08:08PM    <DIR>          docs
06/06/2020  08:08PM             1,100 LICENSE
06/06/2020  08:33PM               291 manage.py
06/06/2020  08:08PM             2,164 README.md
06/06/2020  08:08PM                52 requirements.txt
06/06/2020  08:08PM             1,640 update_version.py
               

D:\django-erp>python manage migrate
python: can't open file 'manage': [Errno 2] No such file or directory

**Comment by DiegoArrieta** [comment]
`python manage.py migrate`

**Comment by santoshmswami** [comment]
D:\django-erp>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\django-erp\djangoerp\pluggets\apps.py", line 23, in <module>
    from .loading import registry
  File "D:\django-erp\djangoerp\pluggets\loading.py", line 21, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (C:\ProgramData\Anaconda3\lib\site-packages\django\utils\__init__.py)

**Comment by srijan113** [comment]
> D:\django-erp>python manage.py migrate
> Traceback (most recent call last):
> File "manage.py", line 11, in
> execute_from_command_line(sys.argv)
> File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management__init__.py", line 401, in execute_from_command_line
> utility.execute()
> File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management__init__.py", line 377, in execute
> django.setup()
> File "C:\ProgramData\Anaconda3\lib\site-packages\django__init__.py", line 24, in setup
> apps.populate(settings.INSTALLED_APPS)
> File "C:\ProgramData\Anaconda3\lib\site-packages\django\apps\registry.py", line 91, in populate
> app_config = AppConfig.create(entry)
> File "C:\ProgramData\Anaconda3\lib\site-packages\django\apps\config.py", line 116, in create
> mod = import_module(mod_path)
> File "C:\ProgramData\Anaconda3\lib\importlib__init__.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1006, in _gcd_import
> File "", line 983, in _find_and_load
> File "", line 967, in _find_and_load_unlocked
> File "", line 677, in _load_unlocked
> File "", line 728, in exec_module
> File "", line 219, in _call_with_frames_removed File "D:\django-erp\djangoerp\pluggets\apps.py", line 23, in from .loading import registry File "D:\django-erp\djangoerp\pluggets\loading.py", line 21, in from django.utils import six ImportError: cannot import name 'six' from 'django.utils' (C:\ProgramData\Anaconda3\lib\site-packages\django\utils__init__.py)


Try using django version less then 3.0

**Comment by zuck** [comment]
Should be fixed now
