### ISSUE TITLE
Django-erp not running in develop environment

### ISSUE THREAD

**Issue by luisza** [django-erp/django-erp#8]
Hi, I am interesting in django-erp, I try to run in develop environment but I have an error.

I used develop branch because I am using django 1.8.4

My environment

* argparse (1.2.1)
* Django (1.8.4)
* django-formtools (1.0)
* pip (1.5.6)
* pytz (2015.4)
* setuptools (5.5.1)
* wsgiref (0.1.2)

My settings modification

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'db.sqlite3',                      # Or path to database file if using sqlite3.
        'USER': '',                      # Not used with sqlite3.
        'PASSWORD': '',                  # Not used with sqlite3.
        'HOST': '',                      # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '',                      # Set to empty string for default. Not used with sqlite3.
    }
}

I create a superuser

       python manage.py createsuperuser 

I have this error when I login as superuser 

![error dj-erp](https://cloud.githubusercontent.com/assets/7146904/9815862/8c375470-5856-11e5-8b37-0b86b205496c.png)
![error2](https://cloud.githubusercontent.com/assets/7146904/9815863/8c5711f2-5856-11e5-943d-a9f577872d16.png)

**Comment by luisza** [comment]
I find the problem and happen when you have non-english system 

    query 	
    u'INSERT INTO "auth_permission" ("name", "content_type_id", "codename") VALUES (?, ?, ?)'

    params 	
    [u'Can view usuario', 2, 'view_user']

But in database 'Can view usuario' not found
![sqlite](https://cloud.githubusercontent.com/assets/7146904/9816591/330abe6e-585b-11e5-9da7-453395421c5c.png)

the issue is in core.managers.PermissionManager in line 66

     name = "Can %s %s" % (action.replace('_', ' '), ct.name)

I changed to  

    name = "Can %s %s" % (action.replace('_', ' '), model_name)

and works now

**Comment by zuck** [comment]
Could you please provide a Pull Request with the suggested change?

**Comment by luisza** [comment]
Hi, I am only testing django-erp, I don't know how it works, so I could provide the PR but I am not sure if it is the best approach or if break something else.

I really not sure if my change works well, because I get those screens 

From / 
![admin](https://cloud.githubusercontent.com/assets/7146904/9858719/759138d6-5adf-11e5-8085-ecb3c3e48377.png)

From /admin/ 
![admin_erp](https://cloud.githubusercontent.com/assets/7146904/9858726/81ca4aa2-5adf-11e5-9de2-e1cd93ff22ce.png)

I think django-erp has other functionalities, so I want to learn more about

**Comment by zuck** [comment]
These are exactly the expected results (at the moment), the project is still at a very early development stage.

So, could you please provide the PR to include this change?

**Comment by zuck** [comment]
Fixed by #11.
