### ISSUE TITLE
Add support for python3

### ISSUE THREAD

**Issue by felixramirezreyes** [django-erp/django-erp#9]
from base import *
ImportError: No module named 'base'

I'm getting this error, please help me
Thanks

**Comment by luisza** [comment]
Did you do the steps 2 and 3  ?

2. Copy and rename djangoerp/settings/base.py.tmpl to djangoerp/settings/base.py.
3. Edit the djangoerp/settings/base.py content.

**Comment by felixramirezreyes** [comment]
Hi!,
Yes, i did it.

Note: I'm using Python 3.4

These are some screen shuts, and the files attached to revise the contents

[image: Imagen integrada 2]


[image: Imagen integrada 4]



2015-09-15 17:36 GMT-04:00 Luis Zárate <notifications@github.com>:

> Did you do the steps 2 and 3 ?
>
>    1. Copy and rename djangoerp/settings/base.py.tmpl to
>    djangoerp/settings/base.py.
>    2. Edit the djangoerp/settings/base.py content.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-erp/django-erp/issues/9#issuecomment-140554108>
> .
>



-- 
*Felix Ramirez R.*

#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013 Emanuele Bertoldi'
__version__ = '0.0.1'

import os
import datetime
from pytz import common_timezones
from django.utils.translation import ugettext_lazy as _

PROJECT_PATH = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.path.pardir))
THEME_PATH = os.path.join(PROJECT_PATH, 'themes', 'default')
REPORT_PATH = os.path.join(PROJECT_PATH, 'reports', 'default')

DEBUG = True
TEMPLATE_DEBUG = DEBUG

ADMINS = (
    # ('Felix Ramirez', 'my_email@domain.com'),
)

MANAGERS = ADMINS

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': '',                      # Or path to database file if using sqlite3.
        'USER': '',                      # Not used with sqlite3.
        'PASSWORD': '',                  # Not used with sqlite3.
        'HOST': '',                      # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '',                      # Set to empty string for default. Not used with sqlite3.
    }
}

# Hosts/domain names that are valid for this site; required if DEBUG is False
# See https://docs.djangoproject.com/en/1.5/ref/settings/#allowed-hosts
ALLOWED_HOSTS = []

# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# although not all choices may be available on all operating systems.
# On Unix systems, a value of None will cause Django to use the same
# timezone as the operating system.
# If running in a Windows environment this must be set to the same as your
# system time zone.
TIME_ZONES = [(tz, tz) for tz in common_timezones]
TIME_ZONE = 'GMT'

# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = 'en'

SITE_ID = 1

# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = True

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale
USE_L10N = True

# If you set this to False, Django will not use timezone-aware datetimes.
USE_TZ = True

# A tuple of directories where Django looks for translation files.
LOCALE_PATHS = (
    os.path.join(PROJECT_PATH, 'settings', 'locale'),
    os.path.join(THEME_PATH, 'locale'),
    os.path.join(REPORT_PATH, 'locale'),
)

# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/home/media/media.lawrence.com/media/"
MEDIA_ROOT = PROJECT_PATH + '/media/'

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://media.lawrence.com/media/", "http://example.com/media/"
MEDIA_URL = '/files/'

# Absolute path to the directory static files should be collected to.
# Don't put anything in this directory yourself; store your static files
# in apps' "static/" subdirectories and in STATICFILES_DIRS.
# Example: "/home/media/media.lawrence.com/static/"
STATIC_ROOT = PROJECT_PATH + '/static/'

# URL prefix for static files.
# Example: "http://media.lawrence.com/static/"
STATIC_URL = '/static/'

# URL prefix for admin static files -- CSS, JavaScript and images.
# Make sure to use a trailing slash.
# Examples: "http://foo.com/static/admin/", "/static/admin/".
ADMIN_MEDIA_PREFIX = '/static/admin/'

# Additional locations of static files
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    THEME_PATH + '/static/',
)

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#    'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

# Make this unique, and don't share it with anybody.
SECRET_KEY = '*7n%@x9c-#f6qn0@(t&7vrx-ddk8fel8fs3xx27wu+dul4rppf'

# List of callables that know how to import templates from various sources.
TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
#     'django.template.loaders.eggs.Loader',
)

# List of processors used by RequestContext to populate the context.
# Each one should be a callable that takes the request object as its
# only parameter and returns a dictionary to add to the context.
TEMPLATE_CONTEXT_PROCESSORS = (
    'django.core.context_processors.debug',
    'django.core.context_processors.i18n',
    'django.core.context_processors.media',
    'django.core.context_processors.static',
    'django.core.context_processors.request',
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
)

# List of search path for templates.
TEMPLATE_DIRS = (
    (os.path.join(THEME_PATH, "templates")),
    (os.path.join(REPORT_PATH, "templates")),
    # Put strings here, like "/home/html/django_templates" or "C:/www/django/templates".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
)

# List of middleware classes to use.  Order is important; in the request phase,
# this middleware classes will be applied in the order given, and in the
# response phase the middleware will be applied in reverse order.
MIDDLEWARE_CLASSES = (
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
    # Uncomment the next line for simple clickjacking protection:
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

# Root for URL dispatcher.
ROOT_URLCONF = 'djangoerp.urls'

# Python dotted path to the WSGI application used by Django's runserver.
WSGI_APPLICATION = 'djangoerp.wsgi.application'

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# A sample logging configuration. The only tangible logging
# performed by this configuration is to send an email to
# the site admins on every HTTP 500 error when DEBUG=False.
# See http://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    }
}

# List of installed applications.
INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.comments',
    'django.contrib.markup',
    'django.contrib.redirects',
    'django.contrib.formtools',

    #'south',
    
    'djangoerp.core',
)

**Comment by luisza** [comment]
I don't know if python 3 is supported.  I tested with python 2.7 and works.

**Comment by felixramirezreyes** [comment]
Thanks any way, i' install 2.7 to test.

Thanks again for your quickly support.

2015-09-15 18:04 GMT-04:00 Luis Zárate <notifications@github.com>:

> I don't know if python 3 is supported. I tested with python 2.7 and works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-erp/django-erp/issues/9#issuecomment-140559737>
> .
>



-- 
*Felix Ramirez R.*

**Comment by zuck** [comment]
The project is not tested on Python3 yet.

**Comment by zuck** [comment]
Python 3 is now supported (please, check d9c9ac9367368debd6cab2e24aecb9220cf4c2f6).

**Comment by greenmails2001** [comment]
I don't know how to do step 3? I'm newbie.
Error at here: from django.db.models.loading import cache
And I dont see database, I'm using sqlite3.
Please help me.
Thanks very much.

**Comment by zuck** [comment]
Are you using **master** or **develop** branch?

**Comment by greenmails2001** [comment]
Dear Mr.Emanuele,
I’m so sorry, i has canceled trying master branch & I'm retrying with develop branch.
This is my developing information:
-	My computer: window8.1-64bit
-	And branch is develop: https://github.com/django-erp/django-erp/tree/develop
-	My Step:
o	Step0: the following pre-requisites installed:
	Python 3.4.4, 
	Pytz-2015.7-py3.4, 
	Django 1.9, 
	I didn’t install apache2 & mod_wsgi 
o	Step1: I don’t get from github that I downloaded the develop.zip file from link: https://github.com/django-erp/django-erp/tree/develop because running “git clone https://github.com/django-erp/django-erp.git” will get master branch, not develop.
o	Step2: I turn on Pycharm and open its terminal, and type: pip install -r requirements.txt, in my computer have only one environment.
o	Step3: Copy djangoerp/settings/base.py.tmpl to new file djangoerp/settings/base.py
o	Step4: Edit content djangoerp/settings/base.py:
	On develop branch, i didn’t edit anything:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'default.db',                      # Or path to database file if using sqlite3.
        'USER': '',                      # Not used with sqlite3.
        'PASSWORD': '',                  # Not used with sqlite3.
        'HOST': '',                      # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '',                      # Set to empty string for default. Not used with sqlite3.
    }
}
o	Step5: Type: python manage migrate, and get error such as the email displayed below.

Best Regards,
LanPhan

**Comment by zuck** [comment]
Could you please try with the following branch also?

https://github.com/zuck/django-erp/tree/feature-semantic-ui-theme

Thank you!

**Comment by greenmails2001** [comment]
Dear,
Finally, I tried with python 2.7, django 1.8.8, then django-erp can runserver (with two branch).
I think using django 1.9 have problem.

Another question:
 I don't know username and password to login?
Could you please to help me again.
Best Regards,
LanPhan

**Comment by luisza** [comment]
You can create your own user using 
    
     $ python manage.py createsuperuser 

See: https://docs.djangoproject.com/en/1.8/ref/django-admin/#createsuperuser

**Comment by greenmails2001** [comment]
Thank Luisza.

**Comment by zuck** [comment]
Support for *Django 1.9* is now tracked in #24.

Thank you for you debugging contribution!

**Comment by desmo90** [comment]
Hello,
i'm testing the master branch and this:
https://github.com/zuck/django-erp/tree/feature-semantic-ui-theme
an get the same error.

**My system:**
* python 3.5.1 and python 2.7.11
* django 1.8.8
* pytz 2016.3

I**'m change the base.py to:**
* 'ENGINE': 'django.db.backends.sqlite3',
* 'NAME': 'database.db',

**and run the fallowing command:**
`python manage.py syncdb`

**and get this error:**

> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 303, in execute
>     settings.INSTALLED_APPS
>   File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 48, in __getattr__
>     self._setup(name)
>   File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 92, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 662, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/django-erp/djangoerp/settings/__init__.py", line 18, in <module>
>     from base import *
> ImportError: No module named 'base'

- I have the same error with Django 1.9
- With Python 2.7.11 this Error:

> Traceback (most recent call last):
>   File "manage.py", line 8, in <module>
>     from django.core.management import execute_from_command_line
> ImportError: No module named django.core.management

**Comment by ssandyy** [comment]
can anyone please help me with default username and password to login
